Update Application_Commands.md
Aiko-IT-Systems/Discord-API-Docs pull request #12
Opened 2022-01-14 17:25 UTC by Lulalaby

2022-01-19 11:42 UTC, FedorLap2006 requested changes
The old endpoints have some naming issues, this PR could fix them as well

2022-01-19 11:42 UTC, FedorLap2006 commented on docs/interactions/Application_Commands.md
>  ## Edit Application Command Permissions % PUT /applications/{application.id#DOCS_RESOURCES_APPLICATION/application-object}/guilds/{guild.id#DOCS_RESOURCES_GUILD/guild-object}/commands/{command.id#DOC
```suggestion
## Edit Guild Application Command Permissions % PUT /applications/{application.id#DOCS_RESOURCES_APPLICATION/application-object}/guilds/{guild.id#DOCS_RESOURCES_GUILD/guild-object}/commands/{command.id#DOCS_INTERACTIONS_APPLICATION_COMMANDS/application-command-object}/permissions
```

2022-01-19 11:42 UTC, FedorLap2006 commented on docs/interactions/Application_Commands.md
>  ## Batch Edit Application Command Permissions % PUT /applications/{application.id#DOCS_RESOURCES_APPLICATION/application-object}/guilds/{guild.id#DOCS_RESOURCES_GUILD/guild-object}/commands/permissio
```suggestion
## Batch Edit Guild Application Command Permissions % PUT /applications/{application.id#DOCS_RESOURCES_APPLICATION/application-object}/guilds/{guild.id#DOCS_RESOURCES_GUILD/guild-object}/commands/permissions
```

2022-01-19 11:44 UTC, Lulalaby commented on docs/interactions/Application_Commands.md
>  ## Batch Edit Application Command Permissions % PUT /applications/{application.id#DOCS_RESOURCES_APPLICATION/application-object}/guilds/{guild.id#DOCS_RESOURCES_GUILD/guild-object}/commands/permissio
Incorrect.

This includes global cmds too

2022-01-19 11:45 UTC, Lulalaby commented on docs/interactions/Application_Commands.md
>  ## Batch Edit Application Command Permissions % PUT /applications/{application.id#DOCS_RESOURCES_APPLICATION/application-object}/guilds/{guild.id#DOCS_RESOURCES_GUILD/guild-object}/commands/permissio
or maybe yes.
but guild ac perm seems wrong due to them be referred to only guild cmds

2022-01-26 07:07 UTC, Lulalaby commented on docs/interactions/Application_Commands.md
> +> To set default permissions, see [Default Permissions](#DOCS_INTERACTIONS_APPLICATION_COMMANDS/default-permissions) for more info.
```suggestion
> To set default permissions, see [Default Permissions](#DOCS_INTERACTIONS_APPLICATION_COMMANDS/default-permissions).
```

2022-01-29 02:46 UTC, closed without merging